name: Build and Deploy Website

on:
  push:
    branches:
      - main  # Replace with your default branch if different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v3

      - name: Replace Token Placeholder
        run: |
          find . -type f \( -name "index.html" -o -name "*.js" \) -exec sed -i 's|Image_Placeholder|${{ secrets.BIRD_TOKENS }}|g' {} +
